#!/bin/bash

TARGET="inc/fwinfo.h"

VERSION_STR=`(git tag --sort=-"v:refname" || echo 0.0.0) | sed -n '1p'`
VERSION_STR=${VERSION_STR#v}

VERSION_MAJOR=${VERSION_STR/.*}
VERSION_STR=${VERSION_STR#$VERSION_MAJOR.}
VERSION_MINOR=${VERSION_STR/.*}
VERSION_STR=${VERSION_STR#$VERSION_MINOR.}
VERSION_REVISION=${VERSION_STR/.*}

COMMIT=`(git log -n 1 --pretty=format:%h || echo 0)`

read BUILD_YEAR BUILD_MONTH BUILD_DAY BUILD_HOUR BUILD_MINUTE BUILD_SECOND <<<`date -u "+%Y %m %d %H %M %S"`

sed \
    -e "s/%FW_VERSION_MAJOR%/$VERSION_MAJOR/" \
    -e "s/%FW_VERSION_MINOR%/$VERSION_MINOR/" \
    -e "s/%FW_VERSION_REVISION%/$VERSION_REVISION/" \
    -e "s/%FW_VERSION%/\"$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION\"/" \
    -e "s/%GIT_COMMIT%/$COMMIT/" \
    -e "s/%BUILD_YEAR%/$BUILD_YEAR/" \
    -e "s/%BUILD_MONTH%/$BUILD_MONTH/" \
    -e "s/%BUILD_DAY%/$BUILD_DAY/" \
    -e "s/%BUILD_HOUR%/$BUILD_HOUR/" \
    -e "s/%BUILD_MINUTE%/$BUILD_MINUTE/" \
    -e "s/%BUILD_SECOND%/$BUILD_SECOND/" \
    -e "s/%BUILD_TIMESTAMP%/\"$BUILD_YEAR-$BUILD_MONTH-$BUILD_DAY $BUILD_HOUR:$BUILD_MINUTE:$BUILD_SECOND\"/" \
    "$TARGET.in" > "$TARGET"
